import type { EnglishItem } from './types';

/** 单词 → 大 emoji（看图选词/选义，无需位图资源） */
const WORD_EMOJI: Record<string, string> = {
  apple: '🍎',
  banana: '🍌',
  orange: '🍊',
  pear: '🍐',
  peach: '🍑',
  grape: '🍇',
  watermelon: '🍉',
  bread: '🍞',
  cake: '🎂',
  egg: '🥚',
  rice: '🍚',
  noodles: '🍜',
  chicken: '🍗',
  fish: '🐟',
  milk: '🥛',
  juice: '🧃',
  tea: '🍵',
  water: '💧',
  cat: '🐱',
  dog: '🐶',
  bird: '🐦',
  rabbit: '🐰',
  mouse: '🐭',
  horse: '🐴',
  cow: '🐮',
  sheep: '🐑',
  pig: '🐷',
  duck: '🦆',
  tiger: '🐯',
  lion: '🦁',
  monkey: '🐵',
  panda: '🐼',
  elephant: '🐘',
  bear: '🐻',
  ball: '⚽',
  car: '🚗',
  bus: '🚌',
  doll: '🪆',
  toy: '🧸',
  book: '📖',
  pencil: '✏️',
  ruler: '📏',
  schoolbag: '🎒',
  desk: '🪑',
  chair: '🪑',
  teacher: '👩‍🏫',
  friend: '🤝',
  dad: '👨',
  father: '👨',
  mom: '👩',
  mother: '👩',
  brother: '👦',
  sister: '👧',
  grandfather: '👴',
  grandmother: '👵',
  baby: '👶',
  boy: '👦',
  girl: '👧',
  man: '👨',
  woman: '👩',
  eye: '👁️',
  ear: '👂',
  nose: '👃',
  mouth: '👄',
  hand: '✋',
  foot: '🦶',
  head: '🙂',
  face: '😊',
  red: '🔴',
  blue: '🔵',
  green: '🟢',
  yellow: '🟡',
  black: '⚫',
  white: '⚪',
  pink: '🩷',
  sun: '☀️',
  moon: '🌙',
  star: '⭐',
  tree: '🌳',
  flower: '🌸',
  grass: '🌿',
  umbrella: '☂️',
  school: '🏫',
  hospital: '🏥',
  park: '🏞️',
  zoo: '🦁',
  home: '🏠',
  bed: '🛏️',
  door: '🚪',
  hat: '🧢',
  cap: '🧢',
  dress: '👗',
  shirt: '👕',
  shoe: '👟',
  socks: '🧦',
  doctor: '👨‍⚕️',
  nurse: '👩‍⚕️',
  driver: '🚗',
  farmer: '👨‍🌾',
  cook: '👨‍🍳',
  basketball: '🏀',
  football: '⚽',
  hello: '👋',
  hi: '👋',
  bye: '👋',
  yes: '✅',
  no: '❌',
  thank: '🙏',
  happy: '😊',
  hungry: '🍽️',
  Christmas: '🎄',
  present: '🎁',
  one: '1️⃣',
  two: '2️⃣',
  three: '3️⃣',
  four: '4️⃣',
  five: '5️⃣',
  six: '6️⃣',
  seven: '7️⃣',
  eight: '8️⃣',
  nine: '9️⃣',
  ten: '🔟',
};

const CATEGORY_EMOJI: Record<string, string> = {
  animal: '🐾',
  fruit: '🍎',
  food: '🍽️',
  drink: '🥤',
  color: '🎨',
  family: '👨‍👩‍👧',
  body: '🧒',
  toy: '🧸',
  school: '📚',
  classroom: '🏫',
  clothes: '👕',
  weather: '🌤️',
  nature: '🌿',
  place: '📍',
  sport: '⚽',
  job: '💼',
  festival: '🎉',
  number: '🔢',
  greeting: '👋',
  feeling: '😊',
  home: '🏠',
  furniture: '🛋️',
  people: '🧑',
  daily: '⏰',
  time: '🕐',
  season: '🍂',
  week: '📅',
};

function normalizeWord(word: string): string {
  return word.toLowerCase().trim().split(/\s+/)[0];
}

export function emojiForEnglishItem(item: EnglishItem): string | null {
  const w = normalizeWord(item.word);
  if (WORD_EMOJI[w]) return WORD_EMOJI[w];
  if (w === 'orange' && item.category === 'color') return '🟠';
  if (item.category && CATEGORY_EMOJI[item.category]) {
    return CATEGORY_EMOJI[item.category];
  }
  return null;
}

export function hasEnglishPicture(item: EnglishItem): boolean {
  return emojiForEnglishItem(item) !== null;
}
